name: Devathlon-mccomput3fr3ak
main: com.github.mccomput3rfr3ak.DevathlonMccomput3rfr3ak.DevathlonMccomput3rfr3ak
version: 0.0.1
author: mccomput3rfr3ak
description: DevAthlon 2014 - mccomput3rfr3ak -- Develop a plugin with special effects for minecraft